name: rls
on: workflow_dispatch
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compressing
        run: |
          rm -f ./README.md
          tar -cvf - ./* | zstd -T0 --ultra -20zvc - > ./njk.tar.zst
      - name: Releasing
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sha="$(openssl sha256 ./njk.tar.zst | cut -d ' ' -f2)"
          gh release delete rolling --cleanup-tag -y || true
          gh release create rolling "./njk.tar.zst#${sha}.sha256" --generate-notes
