name: rls
on: workflow_dispatch
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compressing
        run: tar -cvf - ./* | lz4 -c -6 > ./njk.tar.lz4
      - name: Releasing
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sha="$(sha256sum ./njk.tar.lz4 | cut -d ' ' -f1)"
          gh release create rolling || true
          gh release upload rolling "./njk.tar.lz4#${sha}.sha256" --clobber
